.PHONY: clean All

All:
	@echo "----------Building project:[ Final_Project - Debug ]----------"
	@cd "Final_Project" && "$(MAKE)" -f  "Final_Project.mk"
clean:
	@echo "----------Cleaning project:[ Final_Project - Debug ]----------"
	@cd "Final_Project" && "$(MAKE)" -f  "Final_Project.mk" clean
